### ISSUE TITLE
Feature request: Support "jest" property in package.json

### ISSUE THREAD

**Issue by Meligy** [basarat/god-extra#5]
Hello,
Thanks for the super awesome free VSCode extension.

Would it be possible for the Jest support to use the "jest" top property in "package.json", as an alternative to "jest.config.js"?

Thanks again.

Cheers,

**Comment by basarat** [comment]
It is actually not that hard. 

![image](https://user-images.githubusercontent.com/874898/40030091-ec98251a-582b-11e8-9e1a-c6b6d019556f.png)

But decided not to do it because: 
* Want people to use `jest.config.js` as its a good indication in the root of the project that jest is used for testing.
* Allows future `--config` configuration to provide custom jest config (just like alternate `tsconfig.json`)

PS: Thanks for appreciating the extension :rose:

**Comment by Meligy** [comment]
Um. do you think the extension really needs to enforce its opinion on this one?

I mean: there are a couple of different topics here:

- Is config > package property?
- Should the extension force me to use what is better to provide Jest features?

I can easily agree on the first point, that having a separate config is more superior. But if the team for one reason or another used package property, it's hard to convince them to switch to config when the only immediate difference is that the tool I personally use likes it.

It makes sense if it makes providing some of the features harder or the code too messy, but if not, would adding that barrier be more valuable than removing it?

Certainly your call, and your (awesome) extension. Just wanted to share a few thoughts on the topic.
