### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by TuntematonSotilas** [basarat/god-extra#8]
Hello , is the "Class diagram" functionality of alm-tool  is implemented in TypeScript God ?

**Comment by basarat** [comment]
Not yet. Will be a long while. I'm currently using `tsc -w` to generate the errors. Alm had a full blown language service implementation that allowed me to to build anything I wanted by pluging into the typscript's internals (in addition to a smarter error reporter, driven by which files are open being checked first). 

I'm a bit more chill / balancing my life more, due to high stress but decent pay work, giving me only enough brain capacity to focus on one extra curricular task at a time. Right now its holyjs https://holyjs-piter.ru/en/people/118u8f7b2iqm8wgmq6qk60/, after that probably some book / youtube https://www.youtube.com/basaratali / some react ui guidance.

Thanks for your interest :rose:
